### ISSUE TITLE
Unable to use a plugin

### ISSUE THREAD

**Issue by garrettw** [Practically/yii2-chartjs#20]
I am attempting to use [chartjs-plugin-datalabels](https://chartjs-plugin-datalabels.netlify.app/) and in order to get it working, I have to add not only a `'datalabels'` element to the `clientOptions->plugins` array, but apparently I also need a root-level element called `'plugins'` to register it, as you can see in the documentation [here](https://v2_0_0--chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#registration).
This library does not allow me to do this latter step, because the code in `Chart::run()` only populates `'type'`, `'options'`, and `'data'`, with no way to populate `'plugins'`.

~~Also, I just tried extending your class to override `run()` and add that in, and it still doesn't seem to work, so I'm not sure what I'm doing wrong. Not getting any console errors either.~~ Figured this part out. I was using `'plugins' => ['ChartDataLabels'],` and what I actually needed was `'plugins' => [new \yii\web\JsExpression('ChartDataLabels')],`.
So extending your class to add in 'plugins' did end up working.

**Comment by StuTheWebGuy** [comment]
Glad you got it working! Feel free to put your changes in a PR, as this is a useful addition to the library itself.

Thanks for the support 🚀

**Comment by AdeAttwood** [comment]
Right now the only way to do this will be to register the plugin gloabaly and then use it on all of the charts.

**Comment by AdeAttwood** [comment]
Right now, the only way to do this will be to register the plugin globally and then use it on all the charts. As @StuTheWebGuy said, a PR would be welcome to add that as an option on the chart class.

```js
// Register the plugin to all charts:
Chart.register(ChartDataLabels);
```

Adding config into the `options.plugins.datalabels.*` can be done via the `clientOptions.plugins.datalabels.*`  and adding `dataset.datalabels.*` can be done by creating a new data set class and using that for your dataset sort of like the [ScatterDataset](https://github.com/Practically/yii2-chartjs/blob/8da7f5cc36c10adb7d0f077892e8dd2526467805/src/ScatterDataset.php)

```php
class MyDataset extends BaseDataset
{
    public $datalabels = [];

    public function getDataset()
    {
        return array_merge(parent::getDataset(), ['datalabels' => $this->datalabels]);
    }
}
```

Then using the dataset in your chart.

```php
$chart = Chart::widget([
    'clientOptions' => [
        'plugins' => [
             // Change options for ALL labels of THIS CHART
            'datalabels' => ['color' => '#36A2EB']
        ],
    ],
    'datasets' => [
        [
            'class' => MyDataset::class,
            // Change options only for labels of THIS DATASET
            'datalabels' => ['color' => '#36A2EB'],
            'data' => [
                'Key 1' => 10,
                'Key 2' => 20
            ]
        ]
    ]
]);
```
