### ISSUE TITLE
Scatter charts

### ISSUE THREAD

**Issue by davepractically** [Practically/yii2-chartjs#5]
Modify to allow scatter charts as a type, which requires an amended dataset structure

**Comment by AdeAttwood** [comment]
For this I think we need to split the dataset into two, with an abstract class as the base dataset. This will have all the common code for a dataset. Then each dataset will implement a `getData`  where we can manipulate the data into and `x` and `y` [shown in the docs](https://www.chartjs.org/docs/latest/charts/scatter.html)

@StuTheWebGuy what do you think
